import { PrismaClient } from "@prisma/client"
import bcrypt from "bcryptjs"

const prisma = new PrismaClient()

const CATEGORIES_DATA = [
  { name: "Natuur & Milieu", icon: "🌿", color: "#22c55e" },
  { name: "Onderwijs", icon: "📚", color: "#3b82f6" },
  { name: "Zorg & Welzijn", icon: "❤️", color: "#ef4444" },
  { name: "Sport & Recreatie", icon: "⚽", color: "#f97316" },
  { name: "Cultuur & Kunst", icon: "🎨", color: "#a855f7" },
  { name: "Dieren", icon: "🐾", color: "#84cc16" },
  { name: "Vluchtelingen & Integratie", icon: "🤝", color: "#06b6d4" },
  { name: "Ouderen", icon: "👴", color: "#f59e0b" },
  { name: "Jongeren", icon: "🧒", color: "#ec4899" },
  { name: "Technologie", icon: "💻", color: "#6366f1" },
  { name: "Gezondheid", icon: "🏥", color: "#14b8a6" },
  { name: "Evenementen", icon: "🎉", color: "#f43f5e" },
]

const SKILLS_DATA = [
  "Communicatie", "Organisatie", "Rijbewijs", "IT / Technologie",
  "Marketing", "Taalvaardigheid", "EHBO", "Koken", "Muziek",
  "Fotografie", "Tuinieren", "Coaching / Begeleiding",
  "Administratie", "Creatief denken", "Teamwork", "Lesgeven",
]

const ORGANISATIONS = [
  {
    name: "Groene Toekomst Nederland",
    slug: "groene-toekomst-nederland",
    description: "Wij zetten ons in voor een groener en duurzamer Nederland. Met meer dan 5.000 vrijwilligers werken we aan natuurbescherming, klimaateducatie en duurzame projecten door het hele land.",
    website: "https://groeentoekomst.nl",
    email: "info@groeentoekomst.nl",
    phone: "020-1234567",
    address: "Keizersgracht 123",
    city: "Amsterdam",
    categories: ["Natuur & Milieu"],
    vacancies: [
      {
        title: "Boswachter vrijwilliger",
        description: "Als boswachter vrijwilliger help jij mee met het onderhoud van onze natuurgebieden. Je werkt mee aan snoeien, planten en het monitoren van flora en fauna. Geen ervaring vereist, alleen enthousiasme voor de natuur!",
        city: "Amsterdam",
        location: "Amsterdamse Bos",
        remote: false,
        hours: 4,
        duration: "Doorlopend",
        skills: ["Tuinieren", "Teamwork"],
        categories: ["Natuur & Milieu"],
      },
      {
        title: "Klimaateducator voor scholen",
        description: "Geef gastlessen op basisscholen over klimaatverandering en duurzaamheid. Je krijgt een compleet lespakket en begeleiding. Ideaal voor mensen met affiniteit met onderwijs en milieu.",
        city: "Amsterdam",
        location: "Scholen in de regio Amsterdam",
        remote: false,
        hours: 3,
        duration: "Schooljaar",
        skills: ["Communicatie", "Lesgeven"],
        categories: ["Natuur & Milieu", "Onderwijs"],
      },
    ],
  },
  {
    name: "Stichting Leesplezier",
    slug: "stichting-leesplezier",
    description: "Stichting Leesplezier helpt kinderen en volwassenen die moeite hebben met lezen. We organiseren leesclubs, één-op-één begeleiding en leesevenementen in bibliotheken en scholen.",
    website: "https://leesplezier.nl",
    email: "contact@leesplezier.nl",
    phone: "030-9876543",
    address: "Oudegracht 45",
    city: "Utrecht",
    categories: ["Onderwijs"],
    vacancies: [
      {
        title: "Leesmaatje voor kinderen",
        description: "Word leesmaatje voor een kind van 6-12 jaar dat extra hulp nodig heeft bij het lezen. Eén uur per week maak je echt het verschil. We zoeken geduldige, vriendelijke vrijwilligers die van kinderen houden.",
        city: "Utrecht",
        location: "Bibliotheek Utrecht",
        remote: false,
        hours: 1,
        duration: "Minimaal 6 maanden",
        skills: ["Communicatie", "Coaching / Begeleiding"],
        categories: ["Onderwijs"],
      },
      {
        title: "Social media beheerder",
        description: "Help onze stichting groeien door onze social media kanalen te beheren. Je maakt content, plaatst berichten en reageert op volgers. Kennis van Instagram en Facebook is een pré.",
        city: "Utrecht",
        location: "Thuis / Remote",
        remote: true,
        hours: 3,
        duration: "Doorlopend",
        skills: ["Marketing", "Communicatie"],
        categories: ["Onderwijs", "Technologie"],
      },
    ],
  },
  {
    name: "Hartje Rotterdam Zorg",
    slug: "hartje-rotterdam-zorg",
    description: "Hartje Rotterdam biedt persoonlijke ondersteuning aan eenzame ouderen in Rotterdam. We geloven dat iedereen recht heeft op menselijk contact en verbinding, ongeacht leeftijd of achtergrond.",
    website: "https://hartjerotterdam.nl",
    email: "vrijwilligers@hartjerotterdam.nl",
    phone: "010-5551234",
    address: "Coolsingel 200",
    city: "Rotterdam",
    categories: ["Ouderen", "Zorg & Welzijn"],
    vacancies: [
      {
        title: "Bezoekmaatje voor ouderen",
        description: "Bezoek wekelijks een eenzame oudere in Rotterdam voor een kop koffie en een goed gesprek. Je brengt plezier en verbinding in iemands leven. Geen zorgervaring nodig, alleen warmte en tijd.",
        city: "Rotterdam",
        location: "Thuis bij cliënt",
        remote: false,
        hours: 2,
        duration: "Minimaal 1 jaar",
        skills: ["Communicatie", "Coaching / Begeleiding"],
        categories: ["Ouderen", "Zorg & Welzijn"],
      },
      {
        title: "Vervoersvrijwilliger",
        description: "Breng ouderen met de auto naar afspraken bij de dokter, ziekenhuis of sociale activiteiten. Je rijdt op je eigen momenten, wanneer het jou uitkomt. Rijbewijs B vereist.",
        city: "Rotterdam",
        location: "Rotterdam en omgeving",
        remote: false,
        hours: 4,
        duration: "Doorlopend",
        skills: ["Rijbewijs", "Communicatie"],
        categories: ["Ouderen", "Zorg & Welzijn"],
      },
    ],
  },
  {
    name: "Voedselbank Den Haag",
    slug: "voedselbank-den-haag",
    description: "De Voedselbank Den Haag verstrekt wekelijks voedselpakketten aan meer dan 1.200 gezinnen in Den Haag en omgeving. We werken volledig met vrijwilligers en gedoneerd voedsel.",
    website: "https://voedselbank-denhaag.nl",
    email: "info@voedselbank-denhaag.nl",
    phone: "070-3334455",
    address: "Binckhorstlaan 36",
    city: "Den Haag",
    categories: ["Zorg & Welzijn"],
    vacancies: [
      {
        title: "Sorteerder voedselpakketten",
        description: "Help mee bij het sorteren en inpakken van voedselpakketten op zaterdagochtend. Je werkt samen met een gezellig team van vrijwilligers. Geen ervaring nodig!",
        city: "Den Haag",
        location: "Magazijn Binckhorstlaan",
        remote: false,
        hours: 4,
        duration: "Wekelijks",
        skills: ["Teamwork", "Organisatie"],
        categories: ["Zorg & Welzijn"],
      },
      {
        title: "Chauffeur voedseldistributie",
        description: "Rij mee met onze bestelwagen om voedselpakketten op te halen bij supermarkten en te bezorgen bij het magazijn. Rijbewijs B of BE vereist. Flexibele tijden door de week.",
        city: "Den Haag",
        location: "Den Haag en omgeving",
        remote: false,
        hours: 4,
        duration: "Doorlopend",
        skills: ["Rijbewijs", "Teamwork"],
        categories: ["Zorg & Welzijn"],
      },
    ],
  },
  {
    name: "Dierenasiel Eindhoven",
    slug: "dierenasiel-eindhoven",
    description: "Dierenasiel Eindhoven vangt verloren en mishandelde dieren op en zorgt voor herplaatsing bij liefdevolle baasjes. We hebben dagelijks hulp nodig van dierenliefhebbers.",
    website: "https://dierenasiel-eindhoven.nl",
    email: "vrijwilligers@dierenasiel-eindhoven.nl",
    phone: "040-2223344",
    address: "Stratumsedijk 5",
    city: "Eindhoven",
    categories: ["Dieren"],
    vacancies: [
      {
        title: "Uitlaatservice voor asieldieren",
        description: "Loop dagelijks een rondje met onze asielhonden. Jij geeft ze de beweging en sociale interactie die ze nodig hebben. Perfect voor hondenliefhebbers die actief buiten willen zijn.",
        city: "Eindhoven",
        location: "Dierenasiel Eindhoven",
        remote: false,
        hours: 2,
        duration: "Doorlopend",
        skills: ["Teamwork"],
        categories: ["Dieren"],
      },
      {
        title: "Fotograaf voor adoptieprofielen",
        description: "Maak professionele foto's van onze dieren voor hun adoptieprofielen op de website. Goede foto's vergroten de kans op adoptie enorm. Kennis van fotografie en liefde voor dieren is alles wat je nodig hebt.",
        city: "Eindhoven",
        location: "Dierenasiel Eindhoven",
        remote: false,
        hours: 3,
        duration: "Flexibel",
        skills: ["Fotografie"],
        categories: ["Dieren"],
      },
    ],
  },
  {
    name: "Vluchtelingenwerk Groningen",
    slug: "vluchtelingenwerk-groningen",
    description: "Vluchtelingenwerk Groningen helpt nieuwkomers integreren in de Nederlandse samenleving. We bieden taalmaatjes, praktische ondersteuning en sociale activiteiten aan vluchtelingen en statushouders.",
    website: "https://vluchtelingenwerk-groningen.nl",
    email: "info@vluchtelingenwerk-groningen.nl",
    phone: "050-3125678",
    address: "Gedempte Zuiderdiep 98",
    city: "Groningen",
    categories: ["Vluchtelingen & Integratie"],
    vacancies: [
      {
        title: "Taalmaatje Nederlands",
        description: "Oefen wekelijks Nederlands met een vluchteling of statushouder. Je helpt iemand wegwijs te worden in Nederland door gewoon te praten, dingen uit te leggen en samen te lachen. Geen taaldiploma nodig.",
        city: "Groningen",
        location: "Bibliotheek Groningen of thuis",
        remote: false,
        hours: 2,
        duration: "Minimaal 6 maanden",
        skills: ["Communicatie", "Taalvaardigheid", "Coaching / Begeleiding"],
        categories: ["Vluchtelingen & Integratie", "Onderwijs"],
      },
      {
        title: "Buddy voor statushouders",
        description: "Word buddy voor een statushouder die net in Groningen is aangekomen. Je helpt bij praktische zaken zoals het invullen van formulieren, een fiets zoeken of de weg leren kennen in de stad.",
        city: "Groningen",
        location: "Groningen",
        remote: false,
        hours: 3,
        duration: "6 maanden",
        skills: ["Communicatie", "Organisatie"],
        categories: ["Vluchtelingen & Integratie"],
      },
    ],
  },
  {
    name: "Sportclub Zandvoort Jeugd",
    slug: "sportclub-zandvoort-jeugd",
    description: "Wij bieden kwetsbare jongeren van 8-18 jaar een veilige plek om te sporten en vriendschappen op te bouwen. Sport is onze taal, inclusiviteit onze waarde.",
    website: "https://scz-jeugd.nl",
    email: "info@scz-jeugd.nl",
    phone: "023-5761234",
    address: "Sportspark 1",
    city: "Zandvoort",
    categories: ["Sport & Recreatie", "Jongeren"],
    vacancies: [
      {
        title: "Voetbaltrainer jeugd",
        description: "Train wekelijks een jeugdteam in de leeftijd 8-12 jaar. Je hoeft geen UEFA-licentie te hebben — enthousiasme en geduld zijn genoeg. We zorgen voor begeleiding en een geweldig team.",
        city: "Zandvoort",
        location: "Sportpark Zandvoort",
        remote: false,
        hours: 3,
        duration: "Seizoen",
        skills: ["Coaching / Begeleiding", "Communicatie"],
        categories: ["Sport & Recreatie", "Jongeren"],
      },
      {
        title: "Kantine vrijwilliger",
        description: "Help mee in onze gezellige kantine tijdens thuiswedstrijden. Je verzorgt koffie, frisdrank en snacks voor spelers, ouders en supporters. Gezellig, eenvoudig en heel waardevol!",
        city: "Zandvoort",
        location: "Sportpark Zandvoort",
        remote: false,
        hours: 4,
        duration: "Doorlopend",
        skills: ["Koken", "Teamwork"],
        categories: ["Sport & Recreatie"],
      },
    ],
  },
  {
    name: "Museum de Lakenhal Vrijwilligers",
    slug: "museum-de-lakenhal-vrijwilligers",
    description: "Museum De Lakenhal is het historisch museum van Leiden. We zoeken enthousiaste vrijwilligers die onze bezoekers welkom heten en onze kunstcollectie tot leven brengen.",
    website: "https://lakenhal.nl",
    email: "vrijwilligers@lakenhal.nl",
    phone: "071-5165360",
    address: "Oude Singel 28",
    city: "Leiden",
    categories: ["Cultuur & Kunst"],
    vacancies: [
      {
        title: "Rondleider museum",
        description: "Geef rondleidingen aan bezoekers van alle leeftijden door onze prachtige collectie. Je krijgt een uitgebreide training en eigen inhoudelijke expertise is welkom maar geen vereiste.",
        city: "Leiden",
        location: "Museum De Lakenhal, Leiden",
        remote: false,
        hours: 4,
        duration: "Doorlopend",
        skills: ["Communicatie", "Lesgeven"],
        categories: ["Cultuur & Kunst"],
      },
      {
        title: "Gastvrouw/gastheer receptie",
        description: "Verwelkom bezoekers aan de ingang, verkoop kaartjes en beantwoord vragen. Je bent het eerste gezicht van het museum. Gastvrij, vriendelijk en communicatief.",
        city: "Leiden",
        location: "Museum De Lakenhal, Leiden",
        remote: false,
        hours: 5,
        duration: "Doorlopend",
        skills: ["Communicatie", "Administratie"],
        categories: ["Cultuur & Kunst"],
      },
    ],
  },
  {
    name: "Hospice Goed Leven Breda",
    slug: "hospice-goed-leven-breda",
    description: "Hospice Goed Leven biedt liefdevolle terminale zorg aan mensen in hun laatste levensfase. We zorgen voor een waardige en warme omgeving voor bewoners en hun families.",
    website: "https://goed-leven-breda.nl",
    email: "vrijwilligers@goed-leven-breda.nl",
    phone: "076-5218765",
    address: "Ginnekenweg 200",
    city: "Breda",
    categories: ["Zorg & Welzijn", "Gezondheid"],
    vacancies: [
      {
        title: "Nachtwacht vrijwilliger",
        description: "Zorg je voor rust en aanwezigheid bij onze bewoners tijdens de nacht. Je bent er voor kleine hulpvragen, een gesprek of gewoon een hand vasthouden. Bijzonder en zinvol werk voor mensen met empathie.",
        city: "Breda",
        location: "Hospice Goed Leven, Breda",
        remote: false,
        hours: 8,
        duration: "Doorlopend",
        skills: ["Communicatie", "Coaching / Begeleiding"],
        categories: ["Zorg & Welzijn", "Gezondheid"],
      },
      {
        title: "Kok voor bewoners",
        description: "Bereid liefdevolle maaltijden voor onze bewoners en hun gasten. Je werkt samen met de vaste kok en kookt voor groepen van 10-15 personen. Kookervaring is een pré.",
        city: "Breda",
        location: "Hospice Goed Leven, Breda",
        remote: false,
        hours: 5,
        duration: "Doorlopend",
        skills: ["Koken", "Teamwork"],
        categories: ["Zorg & Welzijn"],
      },
    ],
  },
  {
    name: "CodeKids Amsterdam",
    slug: "codekids-amsterdam",
    description: "CodeKids leert kinderen van 8-16 jaar programmeren in achterstandswijken. We geloven dat digitale vaardigheden voor ieder kind toegankelijk moeten zijn, ongeacht achtergrond.",
    website: "https://codekids.amsterdam",
    email: "hello@codekids.amsterdam",
    phone: "020-6543210",
    address: "Bijlmerplein 500",
    city: "Amsterdam",
    categories: ["Technologie", "Jongeren", "Onderwijs"],
    vacancies: [
      {
        title: "Programmeercoach voor kids",
        description: "Leer kinderen de basics van programmeren met Scratch of Python. Je werkt in kleine groepjes en hoeft geen pedagogisch diploma te hebben. Basiskennis van programmeren en geduld zijn genoeg.",
        city: "Amsterdam",
        location: "Bijlmer, Amsterdam",
        remote: false,
        hours: 3,
        duration: "Schooljaar",
        skills: ["IT / Technologie", "Lesgeven", "Coaching / Begeleiding"],
        categories: ["Technologie", "Jongeren"],
      },
      {
        title: "Workshop organisator",
        description: "Plan en organiseer onze maandelijkse coding workshops. Je zorgt voor locaties, deelnemers en materiaal. Ideaal voor iemand met organisatietalent en affiniteit met technologie.",
        city: "Amsterdam",
        location: "Amsterdam",
        remote: false,
        hours: 4,
        duration: "Doorlopend",
        skills: ["Organisatie", "IT / Technologie"],
        categories: ["Technologie", "Jongeren"],
      },
    ],
  },
  {
    name: "Stichting Duurzaam Tilburg",
    slug: "stichting-duurzaam-tilburg",
    description: "We transformeren Tilburg naar een duurzame stad via buurtmoestuinen, repair cafés en milieueducatie. Samen met bewoners bouwen we aan een groene, circulaire toekomst.",
    website: "https://duurzaamtilburg.nl",
    email: "meedoen@duurzaamtilburg.nl",
    phone: "013-4325678",
    address: "Spoorlaan 350",
    city: "Tilburg",
    categories: ["Natuur & Milieu"],
    vacancies: [
      {
        title: "Moestuin coördinator",
        description: "Beheer onze buurtmoestuin in Tilburg-Noord. Je plant het groeiseizoen, begeleidt vrijwilligers en organiseert oogstdagen. Kennis van tuinieren is een pré maar geen vereiste.",
        city: "Tilburg",
        location: "Buurtmoestuin Tilburg-Noord",
        remote: false,
        hours: 5,
        duration: "Seizoen",
        skills: ["Tuinieren", "Organisatie"],
        categories: ["Natuur & Milieu"],
      },
      {
        title: "Repair Café reparateur",
        description: "Repareer kapotte elektronica, kleding of fietsen bij ons maandelijkse Repair Café. Jij deelt je vakkennis en helpt mensen tegelijk besparen en milieubewuster te leven.",
        city: "Tilburg",
        location: "Wijkcentrum De Sleutel, Tilburg",
        remote: false,
        hours: 4,
        duration: "Maandelijks",
        skills: ["IT / Technologie", "Teamwork"],
        categories: ["Natuur & Milieu", "Technologie"],
      },
    ],
  },
  {
    name: "Muziekschool voor Iedereen",
    slug: "muziekschool-voor-iedereen",
    description: "Wij bieden gratis muziekonderwijs aan kinderen in kansarme gezinnen in de regio Nijmegen. Muziek verbindt, inspireert en opent deuren. Ieder kind verdient de kans om muziek te leren.",
    website: "https://muziekschoolvooriedereen.nl",
    email: "info@muziekschoolvooriedereen.nl",
    phone: "024-3556789",
    address: "Molenstraat 110",
    city: "Nijmegen",
    categories: ["Cultuur & Kunst", "Jongeren"],
    vacancies: [
      {
        title: "Muziekdocent vrijwilliger",
        description: "Geef les in jouw instrument aan kinderen van 6-14 jaar. Of het nu gitaar, piano, viool of drums is — elk instrument is welkom. Je geeft les in kleine groepen of individueel, volledig op je eigen tempo.",
        city: "Nijmegen",
        location: "Muziekschool Nijmegen centrum",
        remote: false,
        hours: 4,
        duration: "Schooljaar",
        skills: ["Muziek", "Lesgeven", "Communicatie"],
        categories: ["Cultuur & Kunst", "Jongeren"],
      },
      {
        title: "Instrumenten reparateur",
        description: "Repareer en onderhoud onze collectie instrumenten zodat ze altijd bespeelbaar zijn. Ervaring met instrumentreparatie is vereist. Je werkt op flexibele tijden vanuit onze werkplaats.",
        city: "Nijmegen",
        location: "Werkplaats Muziekschool Nijmegen",
        remote: false,
        hours: 3,
        duration: "Doorlopend",
        skills: ["Teamwork", "Organisatie"],
        categories: ["Cultuur & Kunst"],
      },
    ],
  },
  {
    name: "GezondLeven Friesland",
    slug: "gezondleven-friesland",
    description: "GezondLeven Friesland promoot gezondheid en preventie in kleine Friese gemeenten. We organiseren beweegactiviteiten, gezondheidscheck-ups en voorlichting voor mensen die de reguliere zorg moeilijk bereiken.",
    website: "https://gezondlevenfriesland.nl",
    email: "contact@gezondlevenfriesland.nl",
    phone: "058-2134567",
    address: "Westersingel 22",
    city: "Leeuwarden",
    categories: ["Gezondheid", "Zorg & Welzijn"],
    vacancies: [
      {
        title: "Beweegcoach voor senioren",
        description: "Begeleid wekelijkse beweeggroepen voor senioren in dorpshuizen en buurtcentra. Je doet eenvoudige oefeningen met hen, stimuleert beweging en zorgt voor gezelligheid. Diploma's zijn een pré.",
        city: "Leeuwarden",
        location: "Diverse locaties Friesland",
        remote: false,
        hours: 3,
        duration: "Doorlopend",
        skills: ["Coaching / Begeleiding", "Communicatie"],
        categories: ["Gezondheid", "Ouderen"],
      },
      {
        title: "Gezondheidsvoorlichter",
        description: "Geef voorlichting over gezonde voeding en leefstijl bij huisartsenpraktijken en scholen in Friesland. Je krijgt materiaal en training van ons. Rijbewijs vereist voor verplaatsingen.",
        city: "Leeuwarden",
        location: "Friesland (diverse locaties)",
        remote: false,
        hours: 4,
        duration: "6 maanden",
        skills: ["Communicatie", "Rijbewijs", "Lesgeven"],
        categories: ["Gezondheid"],
      },
    ],
  },
  {
    name: "Festival de Vriendschap",
    slug: "festival-de-vriendschap",
    description: "Festival de Vriendschap is een jaarlijks gratis buurtfestival in Zwolle dat meer dan 10.000 bezoekers trekt. We vieren diversiteit, verbinding en kunst — volledig gerund door vrijwilligers.",
    website: "https://festivaldvriendschap.nl",
    email: "vrijwilligers@festivaldvriendschap.nl",
    phone: "038-4567890",
    address: "Sassenstraat 15",
    city: "Zwolle",
    categories: ["Evenementen", "Cultuur & Kunst"],
    vacancies: [
      {
        title: "Festivalcoördinator",
        description: "Help bij de organisatie van ons jaarlijkse buurtfestival. Je coördineert vrijwilligersgroepen, leveranciers en het programma. Ruime ervaring met evenementenorganisatie is gewenst.",
        city: "Zwolle",
        location: "Stadscentrum Zwolle",
        remote: false,
        hours: 10,
        duration: "3 maanden aanloop + festivaldag",
        skills: ["Organisatie", "Communicatie"],
        categories: ["Evenementen"],
      },
      {
        title: "Festivalfotograaf",
        description: "Leg de mooiste momenten van ons festival vast. Je foto's worden gebruikt voor social media, de website en pers. We zoeken iemand met een eigen camera en oog voor detail.",
        city: "Zwolle",
        location: "Festival terrein Zwolle",
        remote: false,
        hours: 8,
        duration: "Festivaldag + voorbereiding",
        skills: ["Fotografie", "Creativiteit"],
        categories: ["Evenementen", "Cultuur & Kunst"],
      },
    ],
  },
  {
    name: "Buurtbemiddeling Almere",
    slug: "buurtbemiddeling-almere",
    description: "We helpen buren in conflict met elkaar in gesprek te gaan. Buurtbemiddeling zorgt voor minder escalaties en een prettigere woonomgeving. We werken met getrainde vrijwilligers als bemiddelaars.",
    website: "https://buurtbemiddeling-almere.nl",
    email: "meedoen@buurtbemiddeling-almere.nl",
    phone: "036-5496543",
    address: "Hospitaalweg 5",
    city: "Almere",
    categories: ["Zorg & Welzijn", "Jongeren"],
    vacancies: [
      {
        title: "Buurtbemiddelaar",
        description: "Word gecertificeerd buurtbemiddelaar. Je volgt een tweedaagse training en begeleidt daarna conflicten tussen buren. Neutraal, empathisch en communicatief sterk zijn sleuteleigenschappen.",
        city: "Almere",
        location: "Almere (thuiswerkend)",
        remote: false,
        hours: 4,
        duration: "Doorlopend",
        skills: ["Communicatie", "Coaching / Begeleiding"],
        categories: ["Zorg & Welzijn"],
      },
      {
        title: "Administratief medewerker",
        description: "Ondersteun ons team met administratieve taken: verslagen, planning, archivering. Je werkt grotendeels thuis en bent zo'n 3 uur per week actief. Zelfstandig, accuraat en discreet.",
        city: "Almere",
        location: "Thuis / Remote",
        remote: true,
        hours: 3,
        duration: "Doorlopend",
        skills: ["Administratie", "Organisatie"],
        categories: ["Zorg & Welzijn"],
      },
    ],
  },
  {
    name: "Circus Mirandola Maastricht",
    slug: "circus-mirandola-maastricht",
    description: "Sociaal circus voor kinderen met een beperking of kwetsbare achtergrond. Via jongleren, acrobatiek en theater versterken we het zelfvertrouwen van kinderen die buiten de boot vallen.",
    website: "https://circusmirandola.nl",
    email: "info@circusmirandola.nl",
    phone: "043-3214567",
    address: "Statensingel 24",
    city: "Maastricht",
    categories: ["Cultuur & Kunst", "Jongeren"],
    vacancies: [
      {
        title: "Circuscoach",
        description: "Begeleid kinderen bij circusactiviteiten zoals jongleren, trapeze en theater. Je hoeft geen professionele circusartiest te zijn — enthousiasme, geduld en creativiteit zijn het wichtigste.",
        city: "Maastricht",
        location: "Circustent De Tempel, Maastricht",
        remote: false,
        hours: 4,
        duration: "Seizoen",
        skills: ["Coaching / Begeleiding", "Creatief denken"],
        categories: ["Cultuur & Kunst", "Jongeren"],
      },
      {
        title: "Decorbouwer",
        description: "Bouw en ontwerp decorstukken voor onze jaarlijkse circusshow. Je werkt samen met kinderen en begeleiders. Handigheid en creatief inzicht zijn een must.",
        city: "Maastricht",
        location: "Werkplaats Circus Mirandola",
        remote: false,
        hours: 5,
        duration: "3 maanden",
        skills: ["Creatief denken", "Teamwork"],
        categories: ["Cultuur & Kunst"],
      },
    ],
  },
  {
    name: "Buurtgezinnen.nl Haarlem",
    slug: "buurtgezinnen-haarlem",
    description: "Buurtgezinnen.nl koppelt kwetsbare gezinnen aan steungezinnen uit de buurt. Steungezinnen bieden praktische hulp, een luisterend oor of gewoon gezelligheid. Kleine moeite, groot verschil.",
    website: "https://buurtgezinnen.nl/haarlem",
    email: "haarlem@buurtgezinnen.nl",
    phone: "023-5321098",
    address: "Grote Markt 2",
    city: "Haarlem",
    categories: ["Jongeren", "Zorg & Welzijn"],
    vacancies: [
      {
        title: "Steungezin worden",
        description: "Open jouw gezin eens per maand voor een gezin dat een steuntje in de rug kan gebruiken. Je eet samen, doet activiteiten of geeft gewoon rust en ruimte. Voor gezinnen mét kinderen.",
        city: "Haarlem",
        location: "Thuis",
        remote: false,
        hours: 4,
        duration: "Minimaal 1 jaar",
        skills: ["Communicatie", "Teamwork"],
        categories: ["Jongeren", "Zorg & Welzijn"],
      },
      {
        title: "Coördinator Haarlem",
        description: "Begeleid matches tussen kwetsbare gezinnen en steungezinnen in de regio Haarlem. Je voert intakegesprekken, koppelt gezinnen en houdt contact. Werken met gezinnen in je rugzak? Perfect!",
        city: "Haarlem",
        location: "Haarlem",
        remote: false,
        hours: 6,
        duration: "Doorlopend",
        skills: ["Communicatie", "Organisatie", "Coaching / Begeleiding"],
        categories: ["Jongeren", "Zorg & Welzijn"],
      },
    ],
  },
  {
    name: "Amnesty International Nederland",
    slug: "amnesty-international-nederland",
    description: "Amnesty International zet zich wereldwijd in voor mensenrechten. In Nederland werken duizenden vrijwilligers mee aan campagnes, acties en bewustwording. Word deel van deze mondiale beweging.",
    website: "https://amnesty.nl",
    email: "vrijwilligers@amnesty.nl",
    phone: "020-6262636",
    address: "Keizersgracht 177",
    city: "Amsterdam",
    categories: ["Vluchtelingen & Integratie", "Onderwijs"],
    vacancies: [
      {
        title: "Campagnemedewerker",
        description: "Werk mee aan onze nationale campagnes voor mensenrechten. Je verspreidt informatie, organiseert stands en spreekt mensen aan. Sociaal, overtuigend en gedreven zijn jouw sterkste kanten.",
        city: "Amsterdam",
        location: "Amsterdam en omgeving",
        remote: false,
        hours: 4,
        duration: "Per campagne",
        skills: ["Communicatie", "Marketing"],
        categories: ["Vluchtelingen & Integratie"],
      },
      {
        title: "Content schrijver",
        description: "Schrijf blogs, social posts en nieuwsbrieven voor Amnesty Nederland. Je hebt gevoel voor taal, empathie en een goede pen. Werken op afstand is prima.",
        city: "Amsterdam",
        location: "Remote",
        remote: true,
        hours: 4,
        duration: "Doorlopend",
        skills: ["Communicatie", "Marketing"],
        categories: ["Vluchtelingen & Integratie"],
      },
    ],
  },
  {
    name: "Stichting Present Apeldoorn",
    slug: "stichting-present-apeldoorn",
    description: "Present Apeldoorn verbindt mensen die iets te geven hebben met mensen die iets nodig hebben. We organiseren klusprojekten, activiteiten en ontmoetingen tussen vrijwilligers en kwetsbare burgers.",
    website: "https://present-apeldoorn.nl",
    email: "info@present-apeldoorn.nl",
    phone: "055-5764321",
    address: "Loolaan 25",
    city: "Apeldoorn",
    categories: ["Zorg & Welzijn"],
    vacancies: [
      {
        title: "Klusjesvolontair",
        description: "Help eenzame of kwetsbare mensen met kleine klussen thuis: een lamp ophangen, een kastje in elkaar zetten of de tuin opruimen. Je werkt in koppels op woensdagmiddagen.",
        city: "Apeldoorn",
        location: "Bij mensen thuis, Apeldoorn",
        remote: false,
        hours: 3,
        duration: "Doorlopend",
        skills: ["Teamwork", "Communicatie"],
        categories: ["Zorg & Welzijn", "Ouderen"],
      },
      {
        title: "Projectleider klusprojekten",
        description: "Plan en coördineer klusdagen waarbij groepen vrijwilligers helpen bij grotere renovatieprojecten. Je plant materiaal, mensen en activiteiten. Ervaring met coördineren is een pré.",
        city: "Apeldoorn",
        location: "Apeldoorn",
        remote: false,
        hours: 5,
        duration: "Per project",
        skills: ["Organisatie", "Communicatie"],
        categories: ["Zorg & Welzijn"],
      },
    ],
  },
  {
    name: "Rode Kruis Afdeling Arnhem",
    slug: "rode-kruis-arnhem",
    description: "Het Rode Kruis helpt mensen in nood, dichtbij en ver weg. In Arnhem trainen we EHBO'ers, staan we op evenementen en helpen we vluchtelingen en kwetsbare mensen in onze regio.",
    website: "https://rodekruis.nl/arnhem",
    email: "arnhem@rodekruis.nl",
    phone: "026-4452233",
    address: "Nieuwe Plein 30",
    city: "Arnhem",
    categories: ["Gezondheid", "Zorg & Welzijn"],
    vacancies: [
      {
        title: "EHBO vrijwilliger bij evenementen",
        description: "Sta op evenementen als medische hulpverlener. Je hebt een geldig EHBO-diploma en beschikbaar op weekenden. Wij zorgen voor materiaal, hesje en begeleiding. Zinvol en avontuurlijk!",
        city: "Arnhem",
        location: "Evenementen regio Arnhem",
        remote: false,
        hours: 6,
        duration: "Doorlopend",
        skills: ["EHBO", "Communicatie"],
        categories: ["Gezondheid"],
      },
      {
        title: "Trainer EHBO cursussen",
        description: "Geef EHBO-cursussen aan burgers, bedrijven en scholen. Je bent gecertificeerd EHBO-instructeur of bereid de instructeursopleiding te volgen (vergoed door ons).",
        city: "Arnhem",
        location: "Cursuslocaties Arnhem",
        remote: false,
        hours: 4,
        duration: "Doorlopend",
        skills: ["EHBO", "Lesgeven", "Communicatie"],
        categories: ["Gezondheid"],
      },
    ],
  },
  {
    name: "Dementie Vriendelijk Enschede",
    slug: "dementie-vriendelijk-enschede",
    description: "Wij ondersteunen mensen met dementie en hun mantelzorgers in Enschede en omgeving. Vrijwilligers bieden respijtzorg, begeleiding op activiteiten en gezelschap voor mensen met geheugenproblemen.",
    website: "https://dementienvriendelijk-enschede.nl",
    email: "info@dementievriendelijk-enschede.nl",
    phone: "053-4876543",
    address: "Hengelosestraat 200",
    city: "Enschede",
    categories: ["Ouderen", "Zorg & Welzijn", "Gezondheid"],
    vacancies: [
      {
        title: "Activiteitenbegeleider voor dementie",
        description: "Begeleid activiteitengroepen voor mensen met dementie: muziek, knutselen, wandelen of reminiscentie. Je werkt samen met professionele zorgmedewerkers. Geduld en warme persoonlijkheid zijn essentieel.",
        city: "Enschede",
        location: "Zorgcentra Enschede",
        remote: false,
        hours: 3,
        duration: "Doorlopend",
        skills: ["Communicatie", "Coaching / Begeleiding", "Muziek"],
        categories: ["Ouderen", "Zorg & Welzijn"],
      },
      {
        title: "Respijtzorgvrijwilliger",
        description: "Geef mantelzorgers even pauze door tijdelijk de zorg over te nemen. Je zit bij iemand thuis, doet spelletjes of gaat op stap. Voor mensen met empathie en betrouwbaarheid.",
        city: "Enschede",
        location: "Thuis bij cliënt, Enschede",
        remote: false,
        hours: 4,
        duration: "Doorlopend",
        skills: ["Communicatie", "Coaching / Begeleiding"],
        categories: ["Ouderen", "Zorg & Welzijn"],
      },
    ],
  },
  {
    name: "Vogelwacht Utrecht",
    slug: "vogelwacht-utrecht",
    description: "Vogelwacht Utrecht monitort en beschermt vogelpopulaties in de regio Utrecht. We tellen, ringen, nestkasten plaatsen en educeren over biodiversiteit. Voor echte vogelliefhebbers!",
    website: "https://vogelwacht-utrecht.nl",
    email: "info@vogelwacht-utrecht.nl",
    phone: "030-2891234",
    address: "Maliesingel 12",
    city: "Utrecht",
    categories: ["Natuur & Milieu", "Dieren"],
    vacancies: [
      {
        title: "Vogeltelaar",
        description: "Tel vogels in aangewezen gebieden in de regio Utrecht. Je werkt vroeg in de ochtend, krijgt een telling-protocol en werkt met een app. Interesse in vogels is alles wat je nodig hebt!",
        city: "Utrecht",
        location: "Diverse telgebieden Utrecht",
        remote: false,
        hours: 3,
        duration: "Doorlopend",
        skills: ["Teamwork"],
        categories: ["Natuur & Milieu", "Dieren"],
      },
      {
        title: "Nestkasten plaatser",
        description: "Hang nestkasten op in parken, tuinen en landgoederen om broedgelegenheid te creëren voor vogels. Je werkt in koppels op zaterdag. Rijbewijs is handig maar niet vereist.",
        city: "Utrecht",
        location: "Regio Utrecht",
        remote: false,
        hours: 4,
        duration: "Seizoen (winter/voorjaar)",
        skills: ["Tuinieren", "Teamwork"],
        categories: ["Natuur & Milieu", "Dieren"],
      },
    ],
  },
  {
    name: "Jongerenwerk De Schakel",
    slug: "jongerenwerk-de-schakel",
    description: "Jongerenwerk De Schakel biedt een veilige plek voor jongeren van 12-23 jaar in Rotterdam-Zuid. We organiseren sport, workshops, huiswerkbegeleiding en gesprekken over wat jongeren bezighoudt.",
    website: "https://deschakel-rotterdam.nl",
    email: "info@deschakel-rotterdam.nl",
    phone: "010-4563478",
    address: "Carnissestraat 5",
    city: "Rotterdam",
    categories: ["Jongeren", "Zorg & Welzijn"],
    vacancies: [
      {
        title: "Huiswerkbegeleider",
        description: "Help middelbare scholieren 2x per week met hun huiswerk en leerachterstanden. Je hebt minimaal MBO-niveau en geduld. Vergoeding van reiskosten.",
        city: "Rotterdam",
        location: "Jongerencentrum De Schakel, Rotterdam-Zuid",
        remote: false,
        hours: 4,
        duration: "Schooljaar",
        skills: ["Lesgeven", "Coaching / Begeleiding", "Communicatie"],
        categories: ["Jongeren", "Onderwijs"],
      },
      {
        title: "Sportbegeleider streetwork",
        description: "Organiseer en begeleid sportactiviteiten op straat voor jongeren die niet snel naar een sportclub gaan. Je bouwt een vertrouwensband op en motiveert jongeren actief te blijven.",
        city: "Rotterdam",
        location: "Buitenlocaties Rotterdam-Zuid",
        remote: false,
        hours: 4,
        duration: "Doorlopend",
        skills: ["Coaching / Begeleiding", "Communicatie"],
        categories: ["Jongeren", "Sport & Recreatie"],
      },
    ],
  },
  {
    name: "Stichting Lezen en Schrijven",
    slug: "stichting-lezen-en-schrijven",
    description: "Meer dan 2,5 miljoen Nederlanders zijn laaggeletterd. Stichting Lezen en Schrijven helpt volwassenen beter lezen, schrijven en rekenen — voor meer kansen op werk en in het dagelijks leven.",
    website: "https://lezenenschrijven.nl",
    email: "vrijwilligers@lezenenschrijven.nl",
    phone: "070-3378833",
    address: "Laan van Nieuw Oost-Indië 300",
    city: "Den Haag",
    categories: ["Onderwijs"],
    vacancies: [
      {
        title: "Taalvrijwilliger volwassenen",
        description: "Oefen taal en lezen met een volwassen cursist. Je ontmoet hem of haar 1x per week voor een uur. Je krijgt een training, materialen en begeleiding van ons. Geweldig zinvol werk!",
        city: "Den Haag",
        location: "Bibliotheek of buurtcentrum Den Haag",
        remote: false,
        hours: 1,
        duration: "Minimaal 1 jaar",
        skills: ["Communicatie", "Lesgeven", "Taalvaardigheid"],
        categories: ["Onderwijs"],
      },
      {
        title: "Recruiter vrijwilligers",
        description: "Werf nieuwe taalvrijwilligers via bedrijven, universiteiten en sociale media. Je geeft presentaties, beheert aanmeldingen en bent het eerste contact voor nieuwe vrijwilligers.",
        city: "Den Haag",
        location: "Den Haag",
        remote: false,
        hours: 4,
        duration: "Doorlopend",
        skills: ["Communicatie", "Marketing"],
        categories: ["Onderwijs"],
      },
    ],
  },
  {
    name: "Bergkerk Cultureel Centrum",
    slug: "bergkerk-cultureel-centrum",
    description: "De Bergkerk in Deventer is een monumentale kerk omgebouwd tot bruisend cultureel centrum. We organiseren concerten, exposities, debatavonden en theatervoorstellingen voor een breed publiek.",
    website: "https://bergkerk-deventer.nl",
    email: "meedoen@bergkerk-deventer.nl",
    phone: "0570-614567",
    address: "Bergkerkplein 1",
    city: "Deventer",
    categories: ["Cultuur & Kunst", "Evenementen"],
    vacancies: [
      {
        title: "Zaalmedewerker bij evenementen",
        description: "Zorg voor een warm onthaal bij onze concerten, exposities en theatervoorstellingen. Je hebt taken als kaartcontrole, zaalindeling en barservice. Flexibel inzetbaar op avonden en weekenden.",
        city: "Deventer",
        location: "Bergkerk Deventer",
        remote: false,
        hours: 4,
        duration: "Doorlopend",
        skills: ["Communicatie", "Teamwork"],
        categories: ["Cultuur & Kunst", "Evenementen"],
      },
      {
        title: "Technisch medewerker licht & geluid",
        description: "Bedien licht- en geluidsapparatuur bij onze optredens. Ervaring met PA-installaties is vereist. Je wordt ingepland voor specifieke evenementen en krijgt altijd een briefing vooraf.",
        city: "Deventer",
        location: "Bergkerk Deventer",
        remote: false,
        hours: 5,
        duration: "Per evenement",
        skills: ["IT / Technologie", "Teamwork"],
        categories: ["Cultuur & Kunst"],
      },
    ],
  },
  {
    name: "Zeehondencentrum Pieterburen",
    slug: "zeehondencentrum-pieterburen",
    description: "Het Zeehondencentrum Pieterburen redt, verzorgt en rehabiliteert zieke en gewonde zeehonden. Na herstel worden ze teruggeplaatst in de Waddenzee. Uniek, bijzonder en noodzakelijk werk.",
    website: "https://zeehondencentrum.nl",
    email: "vrijwilligers@zeehondencentrum.nl",
    phone: "0595-526526",
    address: "Hoofdstraat 94a",
    city: "Pieterburen",
    categories: ["Dieren", "Natuur & Milieu"],
    vacancies: [
      {
        title: "Zeehondenverzorger",
        description: "Help bij de dagelijkse verzorging van zieke zeehonden: vissen hakken, bassins reinigen, medicatie geven onder toezicht van dierenartsen. Je werkt in shifts en kan ook intern verblijven.",
        city: "Pieterburen",
        location: "Zeehondencentrum Pieterburen",
        remote: false,
        hours: 8,
        duration: "Minimaal 2 weken aaneengesloten",
        skills: ["Teamwork", "EHBO"],
        categories: ["Dieren"],
      },
      {
        title: "Publieksmedewerker",
        description: "Ontvang bezoekers, leg uit hoe we werken en vertel het verhaal van de zeehonden. Je staat dagelijks in contact met het publiek en beantwoordt vragen over zeehonden en de Waddenzee.",
        city: "Pieterburen",
        location: "Zeehondencentrum Pieterburen",
        remote: false,
        hours: 6,
        duration: "Minimaal 1 week",
        skills: ["Communicatie", "Lesgeven"],
        categories: ["Dieren", "Natuur & Milieu"],
      },
    ],
  },
  {
    name: "Fietsersbond Afdeling Delft",
    slug: "fietsersbond-delft",
    description: "De Fietsersbond zet zich in voor veilig en comfortabel fietsen in Delft. We lobbyen voor betere fietspaden, organiseren fietsinspecties en rijden fietstochten met kwetsbare doelgroepen.",
    website: "https://fietsersbond.nl/delft",
    email: "delft@fietsersbond.nl",
    phone: "015-2126789",
    address: "Phoenixstraat 45",
    city: "Delft",
    categories: ["Sport & Recreatie", "Natuur & Milieu"],
    vacancies: [
      {
        title: "Fietsinstructeur voor senioren",
        description: "Help ouderen veilig (weer) te leren fietsen, ook op e-bikes. Je geeft individuele of groepslessen op rustige locaties. Geduld, rijvaardigheid en vriendelijkheid zijn vereist.",
        city: "Delft",
        location: "Delft en omgeving",
        remote: false,
        hours: 3,
        duration: "Seizoen",
        skills: ["Communicatie", "Coaching / Begeleiding", "Rijbewijs"],
        categories: ["Sport & Recreatie", "Ouderen"],
      },
      {
        title: "Fietspad inspecteur",
        description: "Inspecteer fietsroutes in Delft op gevaarlijke situaties, slechte bestrating of onduidelijke borden. Je rapporteert bevindingen via onze app en levert input voor onze lobby richting gemeente.",
        city: "Delft",
        location: "Fietsroutes Delft",
        remote: false,
        hours: 2,
        duration: "Doorlopend",
        skills: ["Administratie", "Organisatie"],
        categories: ["Sport & Recreatie", "Natuur & Milieu"],
      },
    ],
  },
  {
    name: "Wereldwinkel Amersfoort",
    slug: "wereldwinkel-amersfoort",
    description: "De Wereldwinkel verkoopt eerlijke en duurzame producten van producenten in het Globale Zuiden. We dragen bij aan rechtvaardige handelspraktijken en bewustwording over Fair Trade.",
    website: "https://wereldwinkelamersfoort.nl",
    email: "info@wereldwinkelamersfoort.nl",
    phone: "033-4652345",
    address: "Langestraat 68",
    city: "Amersfoort",
    categories: ["Natuur & Milieu", "Vluchtelingen & Integratie"],
    vacancies: [
      {
        title: "Winkelmedewerker Fair Trade",
        description: "Serveer klanten, vul schappen bij en vertel het verhaal achter eerlijke handel. Je werkt in shifts van 3-4 uur. Geen winkelervaring nodig, wel enthousiasme voor duurzaamheid.",
        city: "Amersfoort",
        location: "Wereldwinkel Langestraat, Amersfoort",
        remote: false,
        hours: 4,
        duration: "Doorlopend",
        skills: ["Communicatie", "Teamwork"],
        categories: ["Natuur & Milieu"],
      },
      {
        title: "Inkoper Fair Trade producten",
        description: "Doe inkoop bij Fair Trade leveranciers en zoek nieuwe producten voor ons assortiment. Je hebt affiniteit met internationale handel en spreekt bij voorkeur Engels of Frans.",
        city: "Amersfoort",
        location: "Remote + kantoor Amersfoort",
        remote: true,
        hours: 5,
        duration: "Doorlopend",
        skills: ["Organisatie", "Taalvaardigheid", "Administratie"],
        categories: ["Natuur & Milieu", "Vluchtelingen & Integratie"],
      },
    ],
  },
  {
    name: "Stichting Vliegend Hert",
    slug: "stichting-vliegend-hert",
    description: "Stichting Vliegend Hert biedt droomuitjes aan kinderen met een ernstige ziekte. Via bijzondere ervaringen zoals een dag op zee, backstage bij een concert of een F1-race geven we onvergetelijke herinneringen.",
    website: "https://vliegendhert.nl",
    email: "doe-mee@vliegendhert.nl",
    phone: "020-5308080",
    address: "Jollemanhof 12",
    city: "Amsterdam",
    categories: ["Jongeren", "Gezondheid", "Evenementen"],
    vacancies: [
      {
        title: "Dagbegeleider bij droomuitjes",
        description: "Begeleid een ziek kind en zijn/haar gezin tijdens een bijzonder uitje. Je zorgt voor een veilige, vrolijke dag en past je aan de wensen van het kind aan. Ervaring met kinderen is vereist.",
        city: "Amsterdam",
        location: "Wisselend (heel Nederland)",
        remote: false,
        hours: 8,
        duration: "Per uitje",
        skills: ["Communicatie", "Coaching / Begeleiding"],
        categories: ["Jongeren", "Gezondheid"],
      },
      {
        title: "Sponsorwerving medewerker",
        description: "Ondersteun ons fundraising team bij het benaderen van bedrijven en particuliere donateurs. Je bent communicatief sterk, persistent en gelooft in onze missie.",
        city: "Amsterdam",
        location: "Remote",
        remote: true,
        hours: 4,
        duration: "Doorlopend",
        skills: ["Communicatie", "Marketing"],
        categories: ["Jongeren"],
      },
    ],
  },
  {
    name: "Taalcafé Den Bosch",
    slug: "taalcafe-den-bosch",
    description: "Taalcafé Den Bosch organiseert wekelijkse taalcafés waar inburgeraars, expats en Nederlanders samenkomen om informeel Nederlands te oefenen. In een warme, laagdrempelige sfeer.",
    website: "https://taalcafe-denbosch.nl",
    email: "hallo@taalcafe-denbosch.nl",
    phone: "073-6154321",
    address: "Kerkstraat 22",
    city: "Den Bosch",
    categories: ["Vluchtelingen & Integratie", "Onderwijs"],
    vacancies: [
      {
        title: "Gespreksleider taalcafé",
        description: "Faciliteer gesprekken aan een tafel met 4-6 deelnemers tijdens onze wekelijkse taalcafés. Je introduceert gespreksonderwerpen en zorgt dat iedereen kan meedoen. Moedertaalsprekers Nederlands gezocht.",
        city: "Den Bosch",
        location: "Café De Proosdij, Den Bosch",
        remote: false,
        hours: 2,
        duration: "Wekelijks",
        skills: ["Communicatie", "Taalvaardigheid"],
        categories: ["Vluchtelingen & Integratie"],
      },
      {
        title: "Organisator taalcafé",
        description: "Regel de locatie, materialen, aanmeldingen en communicatie rondom onze wekelijkse taalcafés. Je werkt grotendeels thuis en besteedt zo'n 4 uur per week aan administratie en planning.",
        city: "Den Bosch",
        location: "Remote + evenementen Den Bosch",
        remote: true,
        hours: 4,
        duration: "Doorlopend",
        skills: ["Organisatie", "Administratie"],
        categories: ["Vluchtelingen & Integratie"],
      },
    ],
  },
]

const VOLUNTEERS = [
  {
    name: "Sophie de Vries",
    email: "sophie.devries@example.nl",
    location: "Amsterdam",
    postcode: "1012 AB",
    age: 24,
    bio: "Ik ben een enthousiaste jonge professional met een passie voor duurzaamheid en onderwijs. In mijn vrije tijd geef ik graag workshops en help ik mee aan milieu-initiatieven in de stad.",
    skills: ["Communicatie", "Marketing"],
    interests: ["Natuur & Milieu", "Onderwijs"],
    availability: ["monday", "wednesday", "evening"],
    maxDistance: 10,
  },
  {
    name: "Lars Janssen",
    email: "lars.janssen@example.nl",
    location: "Rotterdam",
    postcode: "3014 GE",
    age: 31,
    bio: "Software developer overdag, vrijwilliger in de avonduren. Ik geloof dat technologie een krachtig middel is om kwetsbare jongeren kansen te geven. Ik leer ze graag programmeren.",
    skills: ["IT / Technologie", "Lesgeven"],
    interests: ["Technologie", "Jongeren"],
    availability: ["tuesday", "thursday", "evening"],
    maxDistance: 15,
  },
  {
    name: "Fatima El Amrani",
    email: "fatima.elamrani@example.nl",
    location: "Den Haag",
    postcode: "2512 BH",
    age: 28,
    bio: "Zelf als kind naar Nederland gekomen, weet ik als geen ander hoe moeilijk integratie kan zijn. Nu help ik anderen om hun weg te vinden in dit mooie land via taalondersteuning en begeleiding.",
    skills: ["Taalvaardigheid", "Communicatie", "Coaching / Begeleiding"],
    interests: ["Vluchtelingen & Integratie", "Onderwijs"],
    availability: ["saturday", "sunday", "morning"],
    maxDistance: 20,
  },
  {
    name: "Pieter van den Berg",
    email: "pieter.vandenberg@example.nl",
    location: "Utrecht",
    postcode: "3511 KE",
    age: 45,
    bio: "Gepensioneerde chauffeur met veel vrije tijd en energie. Ik rij graag ouderen naar afspraken en help bij klussen. Rijbewijs BE aanwezig. Organiseren en mensen helpen is mijn tweede natuur.",
    skills: ["Rijbewijs", "Organisatie", "Teamwork"],
    interests: ["Ouderen", "Zorg & Welzijn"],
    availability: ["monday", "tuesday", "wednesday", "morning"],
    maxDistance: 25,
  },
  {
    name: "Emma Bakker",
    email: "emma.bakker@example.nl",
    location: "Amsterdam",
    postcode: "1054 WD",
    age: 22,
    bio: "Fotografiestudent die haar skills wil inzetten voor een goed doel. Ik maak graag prachtige foto's bij evenementen en voor organisaties die impact maken. Beschik over professioneel camera-materiaal.",
    skills: ["Fotografie", "Creatief denken", "Marketing"],
    interests: ["Cultuur & Kunst", "Evenementen"],
    availability: ["weekend", "saturday", "sunday"],
    maxDistance: 15,
  },
  {
    name: "Ahmed Yilmaz",
    email: "ahmed.yilmaz@example.nl",
    location: "Rotterdam",
    postcode: "3022 AB",
    age: 35,
    bio: "EHBO-instructeur en sport-enthousiasteling. Ik sta graag op evenementen als medische vrijwilliger en help mensen bewegen en gezond leven. EHBO-diploma geldig tot 2027.",
    skills: ["EHBO", "Communicatie", "Coaching / Begeleiding"],
    interests: ["Gezondheid", "Sport & Recreatie"],
    availability: ["saturday", "sunday", "afternoon"],
    maxDistance: 20,
  },
  {
    name: "Inge Smit",
    email: "inge.smit@example.nl",
    location: "Eindhoven",
    postcode: "5611 AA",
    age: 29,
    bio: "UX-designer met een hart voor maatschappij. Ik help stichtingen en maatschappelijke organisaties met hun online aanwezigheid en communicatie. Beschikbaar in de avonduren en weekenden.",
    skills: ["Marketing", "IT / Technologie", "Communicatie"],
    interests: ["Technologie", "Jongeren", "Onderwijs"],
    availability: ["tuesday", "thursday", "evening"],
    maxDistance: 10,
  },
  {
    name: "Daan Visser",
    email: "daan.visser@example.nl",
    location: "Groningen",
    postcode: "9711 AB",
    age: 26,
    bio: "Bioloog en grote dierenliefhebber. Ik loop graag met honden, help bij natuurmonitoring en zet me in voor biodiversiteit. Snel beschikbaar voor buitenwerk in de vroege ochtend.",
    skills: ["Teamwork", "Tuinieren"],
    interests: ["Natuur & Milieu", "Dieren"],
    availability: ["monday", "friday", "morning"],
    maxDistance: 30,
  },
  {
    name: "Marieke Willems",
    email: "marieke.willems@example.nl",
    location: "Utrecht",
    postcode: "3524 GH",
    age: 41,
    bio: "Leraar basisonderwijs met veel ervaring in begeleiding van kinderen. In mijn vrije tijd geef ik graag bijles of begeleid ik kwetsbare kinderen. Geduldig, enthousiast en vol energie.",
    skills: ["Coaching / Begeleiding", "Lesgeven", "Communicatie"],
    interests: ["Onderwijs", "Jongeren"],
    availability: ["wednesday", "friday", "afternoon"],
    maxDistance: 15,
  },
  {
    name: "Tom de Boer",
    email: "tom.deboer@example.nl",
    location: "Leiden",
    postcode: "2311 AB",
    age: 33,
    bio: "Eventmanager van beroep, vrijwilliger uit passie. Ik organiseer graag evenementen voor goede doelen en weet hoe ik chaos tot een geolied systeem omzet. Communicatie is mijn sterkste kant.",
    skills: ["Organisatie", "Communicatie", "Administratie"],
    interests: ["Evenementen", "Cultuur & Kunst"],
    availability: ["thursday", "friday", "evening"],
    maxDistance: 20,
  },
  {
    name: "Naomi Meijer",
    email: "naomi.meijer@example.nl",
    location: "Amsterdam",
    postcode: "1017 DK",
    age: 27,
    bio: "Taalkundige met een passie voor interculturele communicatie. Ik help vluchtelingen en nieuwkomers graag met taal, cultuur en dagelijkse zaken. Spreek Nederlands, Engels, Frans en een beetje Arabisch.",
    skills: ["Communicatie", "Lesgeven", "Taalvaardigheid"],
    interests: ["Vluchtelingen & Integratie", "Onderwijs"],
    availability: ["tuesday", "wednesday", "morning"],
    maxDistance: 10,
  },
  {
    name: "Joost Mulder",
    email: "joost.mulder@example.nl",
    location: "Tilburg",
    postcode: "5011 AB",
    age: 38,
    bio: "Chauffeur en manusje-van-alles. Ik help graag bij de voedselbank, rij mensen naar afspraken en doe klusjes bij kwetsbare mensen thuis. Rijbewijs B en BE aanwezig.",
    skills: ["Rijbewijs", "Teamwork", "Organisatie"],
    interests: ["Zorg & Welzijn", "Ouderen"],
    availability: ["monday", "wednesday", "friday", "morning"],
    maxDistance: 25,
  },
  {
    name: "Sara van der Laan",
    email: "sara.vanderlaan@example.nl",
    location: "Haarlem",
    postcode: "2011 GG",
    age: 23,
    bio: "Conservatoriumstudente die gratis muziekles wil geven aan kinderen die anders geen toegang hebben tot muziekonderwijs. Ik speel piano en gitaar en kan ook zangles geven.",
    skills: ["Muziek", "Creatief denken", "Lesgeven"],
    interests: ["Cultuur & Kunst", "Jongeren"],
    availability: ["saturday", "sunday", "afternoon"],
    maxDistance: 20,
  },
  {
    name: "Rens Bos",
    email: "rens.bos@example.nl",
    location: "Arnhem",
    postcode: "6811 AB",
    age: 52,
    bio: "Gepensioneerde verpleegkundige met jarenlange ervaring in de ouderenzorg. Ik zet me graag in voor eenzame ouderen en mensen in de laatste levensfase. EHBO-gecertificeerd.",
    skills: ["EHBO", "Communicatie", "Coaching / Begeleiding"],
    interests: ["Gezondheid", "Zorg & Welzijn", "Ouderen"],
    availability: ["tuesday", "thursday", "morning"],
    maxDistance: 15,
  },
  {
    name: "Aisha Okafor",
    email: "aisha.okafor@example.nl",
    location: "Den Haag",
    postcode: "2521 CK",
    age: 31,
    bio: "Rechtenstudente en taalvrijwilliger. Ik help nieuwkomers wegwijs in de Nederlandse bureaucratie en oefen taal met hen. Spreek Nederlands, Engels en Igbo.",
    skills: ["Taalvaardigheid", "Coaching / Begeleiding", "Administratie"],
    interests: ["Vluchtelingen & Integratie", "Onderwijs"],
    availability: ["monday", "friday", "afternoon"],
    maxDistance: 15,
  },
  {
    name: "Bas Gerritsen",
    email: "bas.gerritsen@example.nl",
    location: "Amsterdam",
    postcode: "1091 GH",
    age: 44,
    bio: "IT-projectmanager en vader van twee tieners. Ik geef graag programmeerworkshops aan jongeren in kwetsbare wijken. Geloof sterk in de kracht van technologie als emancipatiemiddel.",
    skills: ["IT / Technologie", "Lesgeven", "Organisatie"],
    interests: ["Technologie", "Onderwijs", "Jongeren"],
    availability: ["wednesday", "saturday", "afternoon"],
    maxDistance: 10,
  },
  {
    name: "Lotte Hendriksen",
    email: "lotte.hendriksen@example.nl",
    location: "Nijmegen",
    postcode: "6511 AB",
    age: 25,
    bio: "Communicatieprofessional met een voorliefde voor cultuur en kunst. Ik help culturele organisaties met hun zichtbaarheid en organiseer graag evenementen. Creatief, sociaal en energiek.",
    skills: ["Communicatie", "Marketing", "Creatief denken"],
    interests: ["Evenementen", "Cultuur & Kunst"],
    availability: ["thursday", "friday", "evening"],
    maxDistance: 20,
  },
  {
    name: "Sander Dijkstra",
    email: "sander.dijkstra@example.nl",
    location: "Enschede",
    postcode: "7511 BD",
    age: 36,
    bio: "Maatschappelijk werker met brede interesse in welzijn en buurtwerk. Ik help graag bij bemiddeling en administratieve ondersteuning voor kwetsbare mensen. Discreet en betrouwbaar.",
    skills: ["Organisatie", "Administratie", "Communicatie"],
    interests: ["Zorg & Welzijn", "Ouderen"],
    availability: ["monday", "tuesday", "morning"],
    maxDistance: 15,
  },
  {
    name: "Kim Wolters",
    email: "kim.wolters@example.nl",
    location: "Zwolle",
    postcode: "8011 AB",
    age: 28,
    bio: "Tuinier en permacultuur-enthousiasteling. Ik help graag bij moestuinen, groene projecten en milieu-educatie. Buiten werken en iets groeiends zien geeft mij voldoening.",
    skills: ["Tuinieren", "Teamwork", "Communicatie"],
    interests: ["Natuur & Milieu", "Dieren"],
    availability: ["saturday", "sunday", "morning"],
    maxDistance: 20,
  },
  {
    name: "Felix Brouwer",
    email: "felix.brouwer@example.nl",
    location: "Maastricht",
    postcode: "6211 AA",
    age: 30,
    bio: "Muzikant en jeugdwerker. Ik gebruik muziek en creatieve expressie om jongeren te begeleiden en hun zelfvertrouwen te vergroten. Ervaring met groepswerk en kwetsbare jongeren.",
    skills: ["Muziek", "Coaching / Begeleiding", "Creatief denken"],
    interests: ["Cultuur & Kunst", "Jongeren"],
    availability: ["tuesday", "friday", "evening"],
    maxDistance: 15,
  },
  {
    name: "Hanna Vermeer",
    email: "hanna.vermeer@example.nl",
    location: "Leiden",
    postcode: "2312 LE",
    age: 48,
    bio: "Docente Nederlands met passie voor taalonderwijs aan volwassenen. Ik help mensen die moeite hebben met lezen en schrijven op weg naar meer kansen. Geduldig en methodisch.",
    skills: ["Lesgeven", "Administratie", "Communicatie"],
    interests: ["Onderwijs", "Vluchtelingen & Integratie"],
    availability: ["monday", "wednesday", "afternoon"],
    maxDistance: 10,
  },
  {
    name: "Ruben Kok",
    email: "ruben.kok@example.nl",
    location: "Rotterdam",
    postcode: "3032 AA",
    age: 21,
    bio: "Informaticasstudent die zijn kennis wil delen met jongeren. Ik geef graag workshops in programmeren en gaming voor kinderen in achterstandswijken. Enthousiast, jong en energiek.",
    skills: ["IT / Technologie", "Creatief denken", "Lesgeven"],
    interests: ["Technologie", "Jongeren"],
    availability: ["wednesday", "friday", "evening"],
    maxDistance: 15,
  },
  {
    name: "Yasmin Khalid",
    email: "yasmin.khalid@example.nl",
    location: "Amsterdam",
    postcode: "1073 AB",
    age: 34,
    bio: "Tolk en vertaler die zich inzet voor nieuwkomers en vluchtelingen. Ik begeleid mensen bij het invullen van formulieren, taalcafés en het leren van de Nederlandse taal. Vloeiend in vijf talen.",
    skills: ["Taalvaardigheid", "Communicatie", "Coaching / Begeleiding"],
    interests: ["Vluchtelingen & Integratie", "Onderwijs"],
    availability: ["tuesday", "thursday", "afternoon"],
    maxDistance: 10,
  },
  {
    name: "Arjan van Dijk",
    email: "arjan.vandijk@example.nl",
    location: "Deventer",
    postcode: "7411 AB",
    age: 56,
    bio: "Met de auto en de nodige ervaring help ik ouderen graag met vervoer naar afspraken. Ik doe ook graag klussen thuis bij mensen die dat zelf niet meer kunnen. Rijbewijs B aanwezig.",
    skills: ["Rijbewijs", "Organisatie", "Teamwork"],
    interests: ["Ouderen", "Zorg & Welzijn"],
    availability: ["tuesday", "thursday", "morning"],
    maxDistance: 30,
  },
  {
    name: "Merel de Graaf",
    email: "merel.degraaf@example.nl",
    location: "Utrecht",
    postcode: "3553 CD",
    age: 32,
    bio: "Freelance fotograaf en communicatiespecialist. Ik leg graag bijzondere momenten vast voor organisaties die een positieve impact maken. Beschikbaar voor evenementen en portretfoto's.",
    skills: ["Fotografie", "Marketing", "Communicatie"],
    interests: ["Evenementen", "Cultuur & Kunst"],
    availability: ["saturday", "sunday", "afternoon"],
    maxDistance: 20,
  },
  {
    name: "Quinten Peters",
    email: "quinten.peters@example.nl",
    location: "Breda",
    postcode: "4811 AB",
    age: 27,
    bio: "Sportief en sociaal. Ik help graag bij sportevenementen als vrijwilliger en sta ook klaar als EHBO'er. Voetbal en hardlopen zijn mijn passies, maar ik zet me in voor alle sporten.",
    skills: ["Teamwork", "EHBO", "Communicatie"],
    interests: ["Sport & Recreatie", "Jongeren"],
    availability: ["saturday", "sunday", "morning"],
    maxDistance: 20,
  },
  {
    name: "Noor van Leeuwen",
    email: "noor.vanleeuwen@example.nl",
    location: "Almere",
    postcode: "1312 AA",
    age: 39,
    bio: "Pedagogisch medewerker en moeder van drie kinderen. Ik begeleid graag kwetsbare gezinnen en jongeren. Ervaring in jeugdzorg en gezinsondersteuning. Warm, betrokken en praktisch.",
    skills: ["Coaching / Begeleiding", "Lesgeven", "Communicatie"],
    interests: ["Jongeren", "Onderwijs", "Zorg & Welzijn"],
    availability: ["monday", "wednesday", "morning"],
    maxDistance: 15,
  },
  {
    name: "Tim Kuiper",
    email: "tim.kuiper@example.nl",
    location: "Groningen",
    postcode: "9713 AB",
    age: 24,
    bio: "Marketingstudent met een hart voor maatschappelijke impact. Ik help organisaties graag met hun digitale marketing, campagnes en social media. Creatief en resultaatgericht.",
    skills: ["IT / Technologie", "Marketing", "Communicatie"],
    interests: ["Technologie", "Natuur & Milieu"],
    availability: ["tuesday", "friday", "evening"],
    maxDistance: 15,
  },
  {
    name: "Esther Otten",
    email: "esther.otten@example.nl",
    location: "Amsterdam",
    postcode: "1065 JG",
    age: 43,
    bio: "Administratief medewerker bij de gemeente overdag, vrijwilligster in de avonduren. Ik help graag ouderen en kwetsbare mensen met administratie, formulieren en digitale vaardigheden.",
    skills: ["Administratie", "Communicatie", "Organisatie"],
    interests: ["Zorg & Welzijn", "Ouderen"],
    availability: ["tuesday", "thursday", "evening"],
    maxDistance: 10,
  },
  {
    name: "Marco van Beek",
    email: "marco.vanbeek@example.nl",
    location: "Eindhoven",
    postcode: "5621 AB",
    age: 37,
    bio: "Sporttherapeut en voetbaltrainer. Ik help kwetsbare jongeren via sport hun zelfvertrouwen op te bouwen. Rijbewijs aanwezig voor vervoer van jeugdteams.",
    skills: ["Rijbewijs", "Teamwork", "Coaching / Begeleiding"],
    interests: ["Sport & Recreatie", "Jongeren"],
    availability: ["wednesday", "saturday", "afternoon"],
    maxDistance: 20,
  },
  {
    name: "Fleur Groen",
    email: "fleur.groen@example.nl",
    location: "Den Haag",
    postcode: "2543 AB",
    age: 26,
    bio: "Muziekdocente en singer-songwriter. Ik geef graag muziekles aan kinderen in kansarme situaties. Piano, gitaar en zang zijn mijn specialiteiten. Muziek verbindt en inspireert.",
    skills: ["Muziek", "Creatief denken", "Lesgeven"],
    interests: ["Cultuur & Kunst", "Jongeren"],
    availability: ["thursday", "saturday", "afternoon"],
    maxDistance: 15,
  },
  {
    name: "Wouter Smeets",
    email: "wouter.smeets@example.nl",
    location: "Nijmegen",
    postcode: "6524 AB",
    age: 50,
    bio: "Huisarts (deels gepensioneerd) die zijn medische kennis wil inzetten voor vrijwilligerswerk. EHBO-trainer en gezondheidsvoorlichter. Zet me in voor ouderen en kwetsbare groepen.",
    skills: ["EHBO", "Coaching / Begeleiding", "Lesgeven"],
    interests: ["Gezondheid", "Ouderen", "Zorg & Welzijn"],
    availability: ["monday", "wednesday", "morning"],
    maxDistance: 20,
  },
  {
    name: "Iris van Veen",
    email: "iris.vanveen@example.nl",
    location: "Utrecht",
    postcode: "3571 AB",
    age: 22,
    bio: "Internationale communicatiestudente die meerdere talen spreekt. Ik help vluchtelingen en nieuwkomers graag bij taalondersteuning en integratie. Open, warm en nieuwsgierig.",
    skills: ["Marketing", "Communicatie", "Taalvaardigheid"],
    interests: ["Vluchtelingen & Integratie", "Jongeren"],
    availability: ["monday", "friday", "afternoon"],
    maxDistance: 10,
  },
  {
    name: "Bram Timmermans",
    email: "bram.timmermans@example.nl",
    location: "Haarlem",
    postcode: "2024 AB",
    age: 41,
    bio: "Landschapsarchitect met groene vingers en een groot hart voor de natuur. Ik begeleid graag buurtmoestuinen, herstelprogramma's voor natuur en dierenwelzijn. Elke zaterdag beschikbaar.",
    skills: ["Tuinieren", "Organisatie", "Teamwork"],
    interests: ["Natuur & Milieu", "Dieren"],
    availability: ["saturday", "morning"],
    maxDistance: 25,
  },
  {
    name: "Lena Jacobs",
    email: "lena.jacobs@example.nl",
    location: "Maastricht",
    postcode: "6218 AB",
    age: 29,
    bio: "Lerares Frans en Nederlands als tweede taal. Ik geef graag taallessen aan vluchtelingen en inburgeraars. Geduldig, methodisch en enthousiast. Beschikbaar in de ochtend- en middaguren.",
    skills: ["Taalvaardigheid", "Lesgeven", "Communicatie"],
    interests: ["Onderwijs", "Vluchtelingen & Integratie"],
    availability: ["monday", "tuesday", "wednesday", "morning"],
    maxDistance: 15,
  },
  {
    name: "David Schouten",
    email: "david.schouten@example.nl",
    location: "Rotterdam",
    postcode: "3061 AB",
    age: 55,
    bio: "Gepensioneerde chauffeur en klusser. Ik breng ouderen graag naar doktersafspraken en help bij praktische klusjes thuis. Rijbewijs B en BE aanwezig. Beschikbaar doordeweeks.",
    skills: ["Rijbewijs", "Administratie", "Teamwork"],
    interests: ["Zorg & Welzijn", "Ouderen"],
    availability: ["monday", "tuesday", "wednesday", "thursday", "morning"],
    maxDistance: 20,
  },
  {
    name: "Anna de Lange",
    email: "anna.delange@example.nl",
    location: "Amersfoort",
    postcode: "3811 AB",
    age: 33,
    bio: "Chef-kok en foodie die haar kookkunsten wil inzetten voor een goed doel. Ik kook graag voor hospices, buurtcentra en mensen in nood. Gezonde, smaakvolle en betaalbare maaltijden zijn mijn passie.",
    skills: ["Koken", "Teamwork", "Creatief denken"],
    interests: ["Zorg & Welzijn", "Evenementen"],
    availability: ["wednesday", "saturday", "afternoon"],
    maxDistance: 15,
  },
  {
    name: "Sven Prins",
    email: "sven.prins@example.nl",
    location: "Zwolle",
    postcode: "8025 AB",
    age: 27,
    bio: "Technische informatica-student en audiovisueel enthousiasteling. Ik help graag bij licht- en geluidstechniek op evenementen en ken mijn weg in IT en multimedia.",
    skills: ["IT / Technologie", "Creatief denken", "Teamwork"],
    interests: ["Technologie", "Evenementen", "Cultuur & Kunst"],
    availability: ["friday", "saturday", "sunday", "evening"],
    maxDistance: 20,
  },
  {
    name: "Roos Huisman",
    email: "roos.huisman@example.nl",
    location: "Leeuwarden",
    postcode: "8911 AB",
    age: 35,
    bio: "Fysiotherapeut die beweegprogramma's voor senioren wil begeleiden. Ik geloof in een actief en gezond ouder worden en help mensen graag op weg. Beschikbaar op dinsdag en donderdagochtend.",
    skills: ["Communicatie", "Coaching / Begeleiding", "EHBO"],
    interests: ["Gezondheid", "Ouderen"],
    availability: ["tuesday", "thursday", "morning"],
    maxDistance: 20,
  },
  {
    name: "Cas van der Hoek",
    email: "cas.vanderhoek@example.nl",
    location: "Apeldoorn",
    postcode: "7311 AB",
    age: 44,
    bio: "Projectmanager en organisatieprofessional. Ik coördineer graag klusprojecten en vrijwilligersgroepen. Rijbewijs aanwezig. Natuur en buurtwerk liggen me na aan het hart.",
    skills: ["Organisatie", "Rijbewijs", "Communicatie"],
    interests: ["Zorg & Welzijn", "Natuur & Milieu"],
    availability: ["tuesday", "wednesday", "afternoon"],
    maxDistance: 25,
  },
]

async function main() {
  console.log("🌱 Seeding database...")

  // ── Admin user ──
  console.log("Creating admin user...")
  const adminPassword = await bcrypt.hash("Admin123!", 12)
  await prisma.user.upsert({
    where: { email: "admin@vrijwilligersmatch.nl" },
    update: {},
    create: {
      name: "Platform Admin",
      email: "admin@vrijwilligersmatch.nl",
      password: adminPassword,
      role: "ADMIN",
      status: "ACTIVE",
      onboarded: true,
    },
  })
  console.log("  ✅ admin@vrijwilligersmatch.nl  /  Admin123!")

  // Create categories
  console.log("Creating categories...")
  const categoryMap: Record<string, string> = {}
  for (const cat of CATEGORIES_DATA) {
    const created = await prisma.category.upsert({
      where: { name: cat.name },
      update: {},
      create: cat,
    })
    categoryMap[cat.name] = created.id
  }

  // Create skills
  console.log("Creating skills...")
  const skillMap: Record<string, string> = {}
  for (const skillName of SKILLS_DATA) {
    const created = await prisma.skill.upsert({
      where: { name: skillName },
      update: {},
      create: { name: skillName },
    })
    skillMap[skillName] = created.id
  }

  // Create organisations and vacancies
  console.log("Creating organisations and vacancies...")
  let orgCount = 0
  let vacancyCount = 0

  const orgPassword = await bcrypt.hash("Org123!", 12)
  console.log("  ✅ Alle organisatie-accounts krijgen wachtwoord: Org123!")

  for (const orgData of ORGANISATIONS) {
    // Create admin user for organisation
    const adminUser = await prisma.user.upsert({
      where: { email: orgData.email },
      update: { password: orgPassword, status: "ACTIVE" },
      create: {
        name: `Admin ${orgData.name}`,
        email: orgData.email,
        password: orgPassword,
        role: "ORGANISATION",
        status: "ACTIVE",
        onboarded: true,
      },
    })

    // Create organisation
    const org = await prisma.organisation.upsert({
      where: { slug: orgData.slug },
      update: {},
      create: {
        name: orgData.name,
        slug: orgData.slug,
        description: orgData.description,
        website: orgData.website,
        email: orgData.email,
        phone: orgData.phone,
        address: orgData.address,
        city: orgData.city,
        status: "APPROVED",
        adminId: adminUser.id,
      },
    })

    // Add organisation categories
    for (const catName of orgData.categories) {
      if (categoryMap[catName]) {
        await prisma.orgCategory.upsert({
          where: {
            organisationId_categoryId: {
              organisationId: org.id,
              categoryId: categoryMap[catName],
            },
          },
          update: {},
          create: {
            organisationId: org.id,
            categoryId: categoryMap[catName],
          },
        })
      }
    }

    orgCount++

    // Create vacancies for this organisation
    for (const vacData of orgData.vacancies) {
      const vacancy = await prisma.vacancy.create({
        data: {
          title: vacData.title,
          description: vacData.description,
          city: vacData.city,
          location: vacData.location,
          remote: vacData.remote,
          hours: vacData.hours,
          duration: vacData.duration,
          status: "ACTIVE",
          organisationId: org.id,
        },
      })

      // Add vacancy skills
      for (const skillName of vacData.skills) {
        if (skillMap[skillName]) {
          await prisma.vacancySkill.upsert({
            where: {
              vacancyId_skillId: {
                vacancyId: vacancy.id,
                skillId: skillMap[skillName],
              },
            },
            update: {},
            create: {
              vacancyId: vacancy.id,
              skillId: skillMap[skillName],
            },
          })
        }
      }

      // Add vacancy categories
      for (const catName of vacData.categories) {
        if (categoryMap[catName]) {
          await prisma.vacancyCategory.upsert({
            where: {
              vacancyId_categoryId: {
                vacancyId: vacancy.id,
                categoryId: categoryMap[catName],
              },
            },
            update: {},
            create: {
              vacancyId: vacancy.id,
              categoryId: categoryMap[catName],
            },
          })
        }
      }

      vacancyCount++
    }
  }

  // Create volunteers
  console.log("Creating volunteers...")
  const volunteerPassword = await bcrypt.hash("Vrijwilliger123!", 12)
  let volunteerCount = 0

  for (const vol of VOLUNTEERS) {
    const user = await prisma.user.upsert({
      where: { email: vol.email },
      update: {
        name: vol.name,
        bio: vol.bio,
        location: vol.location,
        postcode: vol.postcode,
        age: vol.age,
        availability: JSON.stringify(vol.availability),
        maxDistance: vol.maxDistance,
        onboarded: true,
        status: "ACTIVE",
      },
      create: {
        name: vol.name,
        email: vol.email,
        password: volunteerPassword,
        role: "VOLUNTEER",
        status: "ACTIVE",
        onboarded: true,
        bio: vol.bio,
        location: vol.location,
        postcode: vol.postcode,
        age: vol.age,
        availability: JSON.stringify(vol.availability),
        maxDistance: vol.maxDistance,
      },
    })

    // Skills
    for (const skillName of vol.skills) {
      if (skillMap[skillName]) {
        await prisma.userSkill.upsert({
          where: { userId_skillId: { userId: user.id, skillId: skillMap[skillName] } },
          update: {},
          create: { userId: user.id, skillId: skillMap[skillName] },
        })
      }
    }

    // Interests (categories)
    for (const catName of vol.interests) {
      if (categoryMap[catName]) {
        await prisma.userCategory.upsert({
          where: { userId_categoryId: { userId: user.id, categoryId: categoryMap[catName] } },
          update: {},
          create: { userId: user.id, categoryId: categoryMap[catName] },
        })
      }
    }

    volunteerCount++
  }

  console.log(`  ✅ Alle vrijwilliger-accounts krijgen wachtwoord: Vrijwilliger123!`)

  console.log(`✅ Done!`)
  console.log(`   📂 ${CATEGORIES_DATA.length} categorieën aangemaakt`)
  console.log(`   🔧 ${SKILLS_DATA.length} vaardigheden aangemaakt`)
  console.log(`   🏢 ${orgCount} organisaties aangemaakt`)
  console.log(`   📋 ${vacancyCount} vacatures aangemaakt`)
  console.log(`   👤 ${volunteerCount} vrijwilligers aangemaakt`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
